// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCispqWmj5FgDm-BI5ddZL7YTybolmrVWE',
    appId: '1:675011731931:web:599fb78f26361feff547fe',
    messagingSenderId: '675011731931',
    projectId: 'huha6367',
    authDomain: 'huha6367.firebaseapp.com',
    storageBucket: 'huha6367.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUgrjq_02OixFhzuiIZa20HJpbAQC100',
    appId: '1:675011731931:android:37ca736ae38e21edf547fe',
    messagingSenderId: '675011731931',
    projectId: 'huha6367',
    storageBucket: 'huha6367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvjG-a-bIxAYRG-q7m9CwlXdu85pW1CRA',
    appId: '1:675011731931:ios:951364ccb3a86a4af547fe',
    messagingSenderId: '675011731931',
    projectId: 'huha6367',
    storageBucket: 'huha6367.appspot.com',
    iosClientId: '675011731931-46ufiqnvk5ove1rh4getj8mb4ugmpgco.apps.googleusercontent.com',
    iosBundleId: 'com.hello.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvjG-a-bIxAYRG-q7m9CwlXdu85pW1CRA',
    appId: '1:675011731931:ios:951364ccb3a86a4af547fe',
    messagingSenderId: '675011731931',
    projectId: 'huha6367',
    storageBucket: 'huha6367.appspot.com',
    iosClientId: '675011731931-46ufiqnvk5ove1rh4getj8mb4ugmpgco.apps.googleusercontent.com',
    iosBundleId: 'com.hello.testapp',
  );
}
